// Generated by CoffeeScript 1.4.0
(function() {
  var About, Block, CONFIG, TEMPLATES, g, ga, init;

  CONFIG = {
    $cont: $('#block_container'),
    baseUrl: '/'
  };

  TEMPLATES = {
    about: $('#about').html(),
    block: $('#block').html()
  };

  About = function(apiPath) {
    var AboutModel, AboutView;
    AboutModel = Backbone.Model.extend({
      idAttribute: 'id',
      url: apiPath,
      initialize: function() {},
      defaults: {}
    });
    AboutView = Backbone.View.extend({
      el: '#block_container',
      template: TEMPLATES.about,
      initialize: function() {
        var _this;
        _this = this;
        this.model.bind('change', function() {
          return _this.render();
        });
      },
      render: function() {
        var $newItems, data, templ;
        data = {};
        data.item = this.model.toJSON();
        templ = _.template(this.template);
        $newItems = $(templ(data));
        CONFIG.$cont.isotope('insert', $newItems);
        setTimeout(function() {
          return CONFIG.$cont.isotope({
            sortBy: 'number',
            sortAscending: false
          });
        }, 1000);
      }
    });
    return {
      view: AboutView,
      model: AboutModel
    };
  };

  Block = function(apiPath) {
    var BlockCollection, BlockModel, BlockView;
    BlockModel = Backbone.Model.extend({
      idAttribute: 'id',
      initialize: function() {},
      defaults: {}
    });
    BlockCollection = Backbone.Collection.extend({
      model: BlockModel,
      url: apiPath
    });
    BlockView = Backbone.View.extend({
      el: '#block_container',
      template: TEMPLATES.block,
      initialize: function() {
        var _this;
        _this = this;
        this.collection.bind('reset', function() {
          return _this.render();
        });
      },
      render: function() {
        var $newItems, data, templ;
        data = {};
        data.items = this.collection.toJSON();
        templ = _.template(this.template);
        $newItems = $(templ(data));
        CONFIG.$cont.isotope('insert', $newItems);
        setTimeout(function() {
          return CONFIG.$cont.isotope({
            sortBy: 'number',
            sortAscending: false
          });
        }, 1000);
        $('.item-link, .profile-link').tooltip();
      }
    });
    return {
      view: BlockView,
      model: BlockModel,
      collection: BlockCollection
    };
  };

  init = function() {
    var a, am, av, f, fb, fbc, fbv, fc, fv, g, gc, gv, i, ic, iv, p, pc, pv, t, tc, tv;
    CONFIG.$cont.isotope({
      itemSelector: '.page-item',
      layoutMode: 'masonry',
      getSortData: {
        number: function($el) {
          return parseInt($el.attr('data-epoch'), 10);
        }
      }
    });
    $('.main-nav ul li').on('click', 'a', function(e) {
      var filter, loc;
      e.preventDefault();
      filter = $(this).attr('data-filter');
      CONFIG.$cont.isotope({
        filter: filter
      });
      loc = $(this).parent().index();
      console.log(loc);
      $('.main-nav ul li a').removeClass('active');
      $(this).addClass('active');
      $('.the-question').fadeOut(500);
      $('.the-question').eq(loc).delay(500).fadeIn(500);
    });
    $(document).on('mouseenter', '.page-item', function(e) {
      $(this).find('.icon-wrapper').fadeIn(250);
    }).on('mouseleave', '.page-item', function(e) {
      $(this).find('.icon-wrapper').fadeOut(250);
    });
    $('.email-type form').on('click', 'button', function(e) {
      var emailData;
      e.preventDefault();
      emailData = {};
      emailData.email = $('.email-type form input[name=email]').val();
      emailData.message = $('.email-type form textarea[name=message]').val();
      console.log('button clicked');
      $.ajax({
        url: config.baseUrl + '/api/send_email.php',
        data: emailData,
        success: function(data) {
          console.log(data);
          if (data.success) {
            $('.email-type .contact-form').hide();
            $('.email-type .contact-success').show();
          } else {
            alert('there was an issue with send your message');
          }
        }
      });
    });
    /*
        tu = new Block CONFIG.baseUrl+'api/instagram.php'
        tuc = new tu.collection()
        tuv = new tu.view
            collection: tuc
        tuc.fetch()
    */

    fb = new Block(CONFIG.baseUrl + 'api/facebook.php');
    fbc = new fb.collection();
    fbv = new fb.view({
      collection: fbc
    });
    fbc.fetch();
    i = new Block(CONFIG.baseUrl + 'api/instagram.php');
    ic = new i.collection();
    iv = new i.view({
      collection: ic
    });
    ic.fetch();
    t = new Block(CONFIG.baseUrl + 'api/twitter.php');
    tc = new t.collection();
    tv = new t.view({
      collection: tc
    });
    tc.fetch();
    f = new Block(CONFIG.baseUrl + 'api/foursquare.php');
    fc = new f.collection();
    fv = new f.view({
      collection: fc
    });
    fc.fetch();
    g = new Block(CONFIG.baseUrl + 'api/github.php');
    gc = new g.collection();
    gv = new g.view({
      collection: gc
    });
    gc.fetch();
    p = new Block(CONFIG.baseUrl + 'api/projects.php');
    pc = new p.collection();
    pv = new p.view({
      collection: pc
    });
    pc.fetch();
    a = new About(CONFIG.baseUrl + 'api/linkedin.php');
    am = new a.model();
    av = new a.view({
      model: am
    });
    return am.fetch();
  };

  init();

  ga = function() {
    var events;
    events = function() {
      return $(document).on('click', '.main-nav ul li a', function() {
        return _gaq.push(['_trackEvent', 'home_page', 'main_nav', $(this).attr('data-filter')]);
      });
    };
    return {
      events: events
    };
  };

  g = new ga();

  g.events();

  window.About = About;

  window.Block = Block;

}).call(this);
